version: '3.8'

services:

  transconsul-app:
    container_name: transconsul_app
    restart: always
    env_file: .env
    build: .

  nginx:
    container_name: nginx_transconcul
    restart: always
    image: "nginx:latest"
    ports:
      - "127.0.0.1:5086:5086"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - transconsul-app

networks:
  web_network:
    driver: bridge