# Generated by Django 4.2.10 on 2024-02-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Dirección particular'),
        ),
    ]
