# Generated by Django 5.1 on 2024-09-19 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.IntegerField(default=10)),
                ('reservas', models.IntegerField(default=0)),
                ('abogado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(null=True, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descripcion', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_documentos', models.IntegerField(null=True, verbose_name='Documentos')),
                ('lugar', models.CharField(max_length=250, null=True)),
                ('motivo', models.TextField(null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('cancel', 'Cancelada'), ('accept', 'Aceptada'), ('success', 'Completada')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
                ('legalizadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legalizadoras', to=settings.AUTH_USER_MODEL)),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibles', to='citas.disponible')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='citas.tramite')),
            ],
        ),
    ]
