# Generated by Django 4.2.10 on 2024-06-19 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='legalizadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legalizadoras', to=settings.AUTH_USER_MODEL),
        ),
    ]
