# Generated by Django 5.0.2 on 2024-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
    ]
