# Generated by Django 4.2.10 on 2024-02-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='catidad_documentos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='lugar',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='obtencion',
            field=models.BooleanField(default=False),
        ),
    ]
