version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - db_network
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local

networks:
  db_network:
    external: true
